### PR TITLE
.unit-right class and Abstract font colors

### PR DESCRIPTION
**Pull request by iurevych**
1. I've made a small cleanup and added .unit-right class for better compatibility with floats width like .size1of3, .size2of3. cause otherwise last .unit.size1of3 has 1px less width
2. Abstract font colors added. This allows us to use any skins we like without modifying classes. Otherwise if you call red link with .link-red or a.red for example you have to give another class if somewhere in another skin this link is black. Let's give functional classnames ;)

### CODE REVIEW

**Comment by stubbornella** [comment]
can you move colors into /plugins/?

That way we can get a chance to see how people use it before we put in in the main project.

**Comment by shinuza** [comment]
Can you re-format the code to be consistent with the rest of the project?

**Comment by stubbornella** [comment]
Yes.

Sent from my iPhone

On Jun 8, 2011, at 1:05 AM, shinuza
reply@reply.github.com
wrote:

**Comment by iurevych** [comment]
Sorry I've just saw your comments. Please check

**Comment by stubbornella** [comment]
Sorry I didn't catch this before, can you change it to camelCase?

Sent from my iPhone

On Jul 6, 2011, at 1:59 AM, iurevych
reply@reply.github.com
wrote:

**Comment by iurevych** [comment]
enjoy ;)

**Pull request merged**
