### PR TITLE
Name spaced Classes and a few other issues fixed

### PR DESCRIPTION
**Pull request by sams**
Hi Nicole, Jenny & Martin
- Name Spaced Classes (double-Oh heaven) ~ issue #17
- Duplicated import of heading.css in core.css ~ issue #53
- issue #31 I found applied to IE7 and fixed it
- IE7 Tabs ~ Issue #24 was already fixed by some previous commit (the issue should be closed now)

atb - S

### CODE REVIEW

**Comment by martinklepsch** [comment]
Thanks for doing this especially because it was a long discussed topic.

I'm still not sure whether we should remove the dash or not. It's not necessary but increases readability to some point.

I'll try to get some more feedback from other people through the issue tracker and then I'll pull. :)
If the community decides to omit the dash I will also do this (based on what you did).

**Comment by gmclelland** [comment]
for what is worth oo- looks good to me.  Helps keep it readable.  I ran into my first name spacing problem with the most popular Drupal theme (ZEN) http://drupal.org/project/zen which uses div.section classes in it's markup.

Also, I can see this oocss section classes as a problem for people who try to wrap html5 elements with a div.section for people who don't want to rely on javascript shims. http://www.css-101.org/articles/thoughts_on_the_new_html_elements_and_surrogate_divs/

**Comment by stubbornella** [comment]
Could we make a prefix part of a build script? We should also minify and combine files.

**Comment by stubbornella** [comment]
We're going to make a prefix part of a build script, so I'm closing this issue.

**Pull request closed without merging**
