### PR TITLE
Removed .unit because it can be inferred by the presence of the size class

### PR DESCRIPTION
**Pull request by zachharkey**
The .unit class is redundant and does nothing without an additonal size class anyway,
so why not just use the size class. I realize its kind of a long rule, but the benefits 
are that it
- doesn't affect the cascade
- is backward compatible with existing markup
- saves a considerable amount of markup
- reduces user error (one less thing to remember when marking up grids)

P.S. This is my first attempt at collaborating on github and I have no idea if I'm doing it right.

### CODE REVIEW

**Comment by nwe44** [comment]
Interesting idea. You could remove the .size1of1 from your new line: it's being negated on the next line.

**Comment by zachharkey** [comment]
Good point. In fact, I guess the next line (line 4) could be removed now that it doesn't need to override .unit.

**Comment by nwe44** [comment]
I'm wondering if this pull request reduces the modularity that oocss makes so much of. 

In oocss before your changes, one could in theory use .size1of3 to resize, say, an inline element that would be broken if it were floated. Likewise, you could use .unit as a way to float elements not directly related to the grid.

In a sense, unit is extending the sizeof classes, and visa versa, which is in the spirit of oocss.

**Comment by zachharkey** [comment]
Modularity is only useful when modules can be added or removed independently of one another.

The Grid is the module here. 

Neither of the above examples are grid related and should be discouraged in the name preserving the modularity of the Grid. Just like .h1 .h2 .h3 are discouraged from being used on non-headings.

Independence of the Grid from content (and vice versa) is absolutely in the spirit of oocss.

**Comment by nwe44** [comment]
Fair enough.

**Comment by zachharkey** [comment]
Indeed, after spending a few days without .unit I became annoyed by seemingly trivial side effects — for example, I didn't realize how dependent I had become on slipping in a little `.unit{outline:1px solid red;}` to get my bearings. Thank you for the feedback. You guys are great.

**Pull request closed without merging**
