### PR TITLE
Update _pxToEm.scss

### PR DESCRIPTION
**Pull request by MrFjords**
Added a check for if the value 'auto' is passed to the function to deal with cases where auto is desired as an output.  for example:

margin: pxToEm(20px auto, 16px); would output -> margin: 1.25em auto;

### CODE REVIEW

**Comment by stubbornella** [comment]
@mobywhale-chan can you code review this PR?

**Comment by mobywhale-chan** [comment]
@MrFjords Looks good. Thanks!

**Comment by drublic** [comment]
You might also want to use percentage based or other values.
I personally use something similar to

```
@if $value == 0 or type_of($value) != number
```

in my px to rem mixin [over here](https://github.com/drublic/Sass-Mixins/blob/master/partials/_rem.scss#L14-L22).

It might be interesting to use a mixin like that for `rem` too and combine it with the fontSizes mixin.

**Comment by MrFjords** [comment]
If I've needed to use percentages along with ems I tend to go with something like this:

margin: pxToEm(20px, 16px) percentage(20px/$widthOfContent);

**Pull request merged**
