### PR TITLE
Just to make things easier.

### PR DESCRIPTION
**Pull request by lifeiscontent**
I've run all of your code through a beautifier.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
what good is source if you can't read it?

**Comment by SeanJA** [comment]
This doesn't do too much for the readability... it adds spaces?

**Comment by stubbornella** [comment]
yeah, not convinced this beautifier does a good job.

**Comment by lifeiscontent** [comment]
yeah, I just found a weird bug with the beautifier Nevermind, sorry.

**Pull request closed without merging**
