### PR TITLE
Added an rtl version of the grid

### PR DESCRIPTION
**Pull request by arieh**
Hey
I simply switched the directionality of the grid (right>left and vise versa).
simple tests seem to work

### CODE REVIEW

**Comment by stubbornella** [comment]
This seems pretty cool. Did you test with the two grids test pages on all browsers (IE6-9, FF, Safari, Chrome)?

**Comment by arieh** [comment]
just did :) as far as I can tell this shouldn't change much. All I did was replace the float's direction.

**Comment by arieh** [comment]
I have made some changes to make it more modular:
1. added an rtl class that will activate rtl mode. this has 2 benefits: a) it only requires one change to add it b) it can be applied to specific sections in the page
2. only left the necessary changes (previous version included everything)
3. added this to the main file so since it makes less sense to me to split it

this has been checked on latest chrome, FF 3.6 and IE8 & 6 (which I think is the main range of bugs no?)

**Comment by stubbornella** [comment]
I like this commit a lot. Can you put it in it's own file since a lot of sites are only one direction?

core/grids/grids_rtl.css

**Comment by arieh** [comment]
will do it over this weekend

**Pull request closed without merging**
